homeassistant:
  # Name of the location where Home Assistant is running
  name: 朱小波的家
  # Location required to calculate the time the sun rises and sets
  latitude: 31.0456
  longitude: 121.3997
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    #- /local/custom_ui/state-card-diy.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    #- /local/custom_ui/state-card-diy.html
# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: 123456
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr           
    name: weather
    forecast: 24           #未来24小时天气，可有手工按需修改
    monitored_conditions:
      - temperature        #气温
      - precipitation      #雨量
      - windSpeed          #风速
      - pressure           #气压
      - windDirection      #风向
      - humidity           #湿度

# Text to speech
tts:
  - platform: baidu
    #app_id，api_key，secret_key从百度云上注册得到
    app_id: 11337674 
    api_key: XtR74Qq3EvCRQNiLT7fHGna1
    secret_key: XMeYTwjGOI4k6hC8PkTqM9nRew3Ehszt 
    #speed：语速0-9（缺省5）pitch：语调0-9（缺省5）
    volume: 15 #音量0-15（缺省5）
    #person：声音（0：女，1：男，3：百度合成，4：百度合成，缺省0）
    speed: 5
    pitch: 5
    person: 0
    
media_player :
  - platform: vlc
    name: vlc
    
# Cloud
cloud:

switch:
  platform: wake_on_lan
  friendly_name: 电脑电源
  mac_address: "00-E0-70-6B-40-33"
  host: "192.168.1.142"
  turn_off:
    service: shell_command.turn_off_pc

notify:
  - name: my_notify
    platform: alert_over
    from_source: s-003b4305-8753-4290-9b56-3ec11cc7

shell_command:
    musicbox_play: killall shairport ; su - pi -c 'tmux new-session -d -s  musicbox musicbox -c "?"'
    musicbox_kill: /home/pi/shairport/shairport -a pi -d ; su - pi -c 'tmux kill-session -t musicbox'
    pi_shutdown: halt
    turn_off_pc: 'curl -X GET http://192.168.1.142:8000/?action=System.Shutdown'

group     : !include groups.yaml
automation: !include automations.yaml
script    : !include scripts.yaml

logger:
  default: info
  logs:
    homeassistant.components.shell_command: info


  
